name: Main Workflow

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]     # Publish semver tags as releases.

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write
  security-events: write


jobs:
  call-workflow:
    uses: tychodev321/workflow-templates/.github/workflows/container-publish.yml@main
